{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace.name | default "todo-app" }}
  labels:
    app: {{ .Chart.Name }}-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: 5000
  selector:
    app: api
{{- end }}