{{- if .Values.mssql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: {{ .Values.namespace.name | default "todo-app" }}
  labels:
    app: {{ .Chart.Name }}-mssql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  SA_PASSWORD: {{ .Values.mssql.secrets.saPassword | b64enc | quote }}
  DB_NAME: {{ .Values.mssql.secrets.dbName }}
  DB_HOST: {{ .Values.mssql.secrets.dbHost }}
  DB_USER: {{ .Values.mssql.secrets.dbUser }}
  DB_PASSWORD: {{ .Values.mssql.secrets.dbPassword | b64enc | quote }}
{{- end }}