{{- if .Values.mssql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: {{ .Values.namespace.name | default "todo-app" }}
  labels:
    app: {{ .Chart.Name }}-mssql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: "{{ .Values.mssql.image.repository }}:{{ .Values.mssql.image.tag }}"
        imagePullPolicy: {{ .Values.mssql.image.pullPolicy }}
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql
        resources:
          {{- toYaml .Values.mssql.resources | nindent 10 }}
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
          runAsNonRoot: true
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-pvc
{{- end }}