{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: {{ .Values.namespace.name | default "todo-app" }}
  labels:
    app: {{ .Chart.Name }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.redis.secrets.password | b64enc | quote }}
{{- end }}