apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: todo-app
type: Opaque
stringData:
  SA_PASSWORD: 'Sandip@123'
  DB_NAME: 'TodoDb'
  DB_HOST: 'mssql-service'
  DB_USER: 'sa'
  DB_PASSWORD: 'Admin@123'
