apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      initContainers:
      - name: setup-db
        image: mcr.microsoft.com/mssql-tools
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Waiting for SQL Server to be ready..."
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P "$(SA_PASSWORD)" -Q "SELECT 1"
            echo "SQL Server is ready. Running setup script..."
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P "$(SA_PASSWORD)" -i /config/setup.sql
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        volumeMounts:
        - name: setup-script
          mountPath: /config
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        - name: MSSQL_DB_NAME
          value: "TodoDb"
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-storage
        emptyDir: {}
      - name: setup-script
        configMap:
          name: mssql-setup-script-cm