apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: todo-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_DATABASE: todos
  MYSQL_USER: admin
  MYSQL_PASSWORD: Sandip@123
  MYSQL_HOST: mysql
