apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: todo-app
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: node-api
            port:
              number: 5000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-ui
            port:
              number: 80
      - path: /redis
        pathType: Prefix
        backend:
          service:
            name: redis
            port:
              number: 6379