name: Build and Push Node API to ACR

permissions:
  contents: read

on:
  push:
    paths:
      - 'node-api/**'

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: node-api
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Docker Build and Push
      run: |
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG ./node-api
        az acr login --name ${{ secrets.ACR_NAME }}
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

        # Optional: also push as "latest"
        docker tag $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
