name: Build and Push Node API to ACR

permissions:
  contents: write

on:
  push:
    paths:
      - 'node-api/**'

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: node-api
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Docker Build and Push
      run: |
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG ./node-api
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
    
    - name: Update deployment.yaml with new image tag
      run: |
        # Update the deployment.yaml file to use the new image tag
        sed -i "s|image: k8sdemoproject.azurecr.io/$IMAGE_NAME:.*|image: k8sdemoproject.azurecr.io/$IMAGE_NAME:$IMAGE_TAG|" k8s/api-deployment.yaml
        
        # Commit the updated deployment.yaml file to the Git repository
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add k8s/api-deployment.yaml
        git commit -m "Update API image tag to $IMAGE_TAG"
        git push
